### ISSUE TITLE
Use list to reference backport PR for more metadata

### ISSUE THREAD

**Issue by mweinelt** [korthout/backport-action#243]
This has the benefit that GitHub will show a more detailed view with title and status.

![image](https://user-images.githubusercontent.com/131599/170557227-f8001604-4638-4537-8d00-ae388b0f24be.png)

```
Successfully created backport PR #174766 for `release-22.05`.
```

vs

![image](https://user-images.githubusercontent.com/131599/170557306-920d2b2c-3eb0-4250-9816-67114e4200cc.png)

```
Successfully created backport PR for `release-22.05`:
- #174766
```

**Comment by korthout** [comment]
Available for usage in tag: `v1.next-preview`
