### ISSUE TITLE
Support skipping merge commits

### ISSUE THREAD

**Issue by korthout** [korthout/backport-action#373]
**Is your feature request related to a problem? Please describe.**
Repositories commonly update pull requests with changes from the base using a merge commit. But, the action does not support the cherry-picking of merge commits. So, it fails to backport.

**Describe the solution you'd like**
We can allow users to decide how to deal with merge commits using a new input. This input defaults to the current behavior and allows users to skip merge commits instead.

**Describe alternatives you've considered**
Alternatively, the `mainline` flag can be used to decide how to cherry-pick the merge commit. We consider this a separate feature request which is covered by #341. If you have a need for that, please let us know there.

**Comment by korthout** [comment]
Released in `v1.4.0`, `v1.4`, and `v1`, which now support the new [`merge_commits`](https://github.com/korthout/backport-action#merge_commits) input.

FYI @tdonohue @houserx-jmcc

**Comment by korthout** [comment]
@dlavrenuek I think you may also be interested in this new input.

**Comment by tdonohue** [comment]
Thank you so much @korthout !  I just got around to testing this new `merge_commits: 'skip'` option and it works **perfectly** for our needs.  Merge commits are skipped automatically and not included in the port PR.
