### ISSUE TITLE
ability to backport a PR to any repo, not necessarily a fork

### ISSUE THREAD

**Issue by mvayngrib** [korthout/backport-action#384]
**Is your feature request related to a problem? Please describe.**

forks get detached for one reason or another, but backporting between repos can still be useful

**Describe the solution you'd like**

a github repo option, e.g. `target_repo`(s), to specify to which repo to send the backport PR

**Describe alternatives you've considered**
not sure what the alternatives would be 😅

**Comment by korthout** [comment]
That is a great idea!

The `target_repo` input would take something in the form of `owner/repo` defaulting to the current repo on which the action is run.

This feature would require changing the following:
- add an extra remote for the target repo, i.e. target remote
- git fetch of target branch from target remote
- git push of backport branch to target remote
- create pull request on target repo
- label pull request on target repo

**Comment by mvayngrib** [comment]
i was thinking about it and it might make more sense to support a field `targets` of the format `owner1/repo1/branch1,owner2/repo2/branch2` to avoid getting confused with combinations of target_repo and target_branches

**Comment by korthout** [comment]
Resolved by #405 and released in [v3.0.0](https://github.com/korthout/backport-action/releases/tag/v3.0.0).
