### ISSUE TITLE
Instructions for manually cherry-picking are incorrect as they do not skip merge commits

### ISSUE THREAD

**Issue by jrhemstad** [korthout/backport-action#395]
**Describe the bug**

When the automatic backport fails due to conflicts in cherry-picking individual commits it will helpfully give instructions on how to manually do the cherry-pick:

```
git fetch origin branch/2.3.x
git worktree add -d .worktree/backport-574-to-branch/2.3.x origin/branch/2.3.x
cd .worktree/backport-574-to-branch/2.3.x
git checkout -b backport-574-to-branch/2.3.x
ancref=$(git merge-base 83b3365bbc12a9db248b67c22052413d41fae97e 9e9fb70b712a6799791997d3c70db6a28a71af72)
git cherry-pick -x $ancref..9e9fb70b712a6799791997d3c70db6a28a71af72
```

However, these instructions aren't correct if the PR contains merge commits as it omits the logic for filtering out merge commits. 

**To Reproduce**
1. Create and merge a pull request with merge commits that also will have merge conflicts on the target branch
2. Trigger the backport workflow
3. Backport fails and comments instructions on manual cherry-picking

**Expected behavior**
The instructions should include how to filter out merge commits. 

**Workflow run logs**
https://github.com/NVIDIA/cccl/actions/runs/6750303904/job/18352417643

**Comment by korthout** [comment]
Fixed in [`v2.1.1`](https://github.com/korthout/backport-action/releases/tag/v2.1.1)
