### ISSUE TITLE
Get The successful PR numbers as an output of the action

### ISSUE THREAD

**Issue by GuyAv46** [korthout/backport-action#403]
### **Is your feature request related to a problem? Please describe.**

This request is related to the problem of [triggering workflows from another workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow). I Don't like the solution of using PAT of some user that then gets the responsibility and ownership over the comments and the generated PRs.

In my case, the workflow I need to trigger can be triggered by un-drafting the PR. So the solution I'm thinking about is to have the following steps for the backporting job:

1. checkout
2. backport action, using the default `GITHUB_TOKEN`
3. [convert the PRs to draft](https://cli.github.com/manual/gh_pr_ready) ones using the `gh` CLI using a PAT
4. convert the PRs back to "ready for review" using the `gh` CLI using a PAT again

This way I get the default behavior of the action-bot commenting and opening the PRs, but also triggering the workloads I need. One link is missing though...

### **Describe the solution you'd like**

There is no simple way of getting the PRs that the action generated at the moment. I wish the action could output the new PR numbers as an output, so I could go over them and perform this additional steps.

I believe this could be a useful output for other users with other scenarios as well.

Additional option is to enable the PRs to be created as draft by the action. Will save me an API call but not much more :)

**Comment by korthout** [comment]
Released in [`v2.3.0`](https://github.com/korthout/backport-action/releases/tag/v2.3.0)
