### ISSUE TITLE
Support rebase/squash merges

### ISSUE THREAD

**Issue by korthout** [korthout/backport-action#46]
Currently the action does not support rebase (and squash) merges.

Specifically, this action was build to deal with octopus merges. It does this by looking at the common ancestor of the head and base refs. But after a rebase the branch no longer points to the same head ref, which then ends up not being fetched by the action on checkout.

We should implement an alternative strategy to find all commits merged by the pull request.

**UPDATE**: With `v1` the action no longer looks for the common ancestor, so it should support rebase/squash merges now. Please reach out if you've tried this out (both success and failure stories are appreciated), as I'd like to know whether we can consider this to be supported nowadays.

**Comment by korthout** [comment]
An idea is to use [List commits on a pull request](https://docs.github.com/en/rest/reference/pulls#list-commits-on-a-pull-request), but the documentation is unclear about which commits will be listed. It might mean the original commits before the rebase or the commits after the rebase. Additionally, this requires dealing with pagination (max 100, default 30 per page) and has a maximum limit of requesting 250 commits.

**Comment by domenkozar** [comment]
It would be great if it reported back that this is not supported currently.

**Comment by korthout** [comment]
As far as I could find, it is currently not possible to know how the pull request was merged (merge commit, rebase or squash). 

What I could do is add a check to see whether the commits are available to the action and if not comment on the pull request with something like:
```
Unable to backport this pull request automatically.
Please cherry-pick the commit(s) manually.
It seems that one or more of the commits are not available to the backport-action.
Note that rebase and squash merges are not supported at this time.
For more information see https://github.com/zeebe-io/backport-action/issues/46.
```

Does that help?

**Comment by domenkozar** [comment]
That's great!

**Comment by korthout** [comment]
@domenkozar I've merged a PR that performs this check and comments if 1 of the references cannot be found. Please let me know if you run into any problems with it.

**Comment by domenkozar** [comment]
Thank you :)

**Comment by domenkozar** [comment]
It doesn't seem to work: https://github.com/NixOS/nixpkgs/pull/143639#issuecomment-955071800
